---
- include_tasks: hub.yml

#- name: Update packages
  #become: yes
  #apt: upgrade=dist update_cache=yes
  #tags: package

- name: Install libraries using package manager
  package: name={{ item }} state=present
  become: yes
  become_method: sudo
  with_items:
    #- ack-grep  # Unavailable on ubuntu 17.10
    - bash
    - bat
    - curl
    - exa
    - git
    - highlight
    - htop
    - nmap
    - python3
    - tmux
    - tree
    - vim
    - wget
    - zsh
  tags: package

- name: Change shell to ZSH
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name=chaudhary
  # TODO: Change chaudhary to variable user
